# Generated by Django 3.1.5 on 2021-01-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210126_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='bloodgroup',
        ),
        migrations.AddField(
            model_name='hospital',
            name='bloodgroup',
            field=models.ManyToManyField(to='catalog.BloodGroup'),
        ),
    ]
