# Generated by Django 3.1.5 on 2021-01-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210126_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='bloodgroup',
        ),
    ]
