# Generated by Django 3.1.5 on 2021-01-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_hospital_bloodgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PintsAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(null=True)),
                ('bloodgroup', models.ManyToManyField(to='catalog.BloodGroup')),
            ],
        ),
    ]
