# Generated by Django 3.1.5 on 2021-01-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pintsavailable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pintsavailable',
            name='bloodgroup',
        ),
        migrations.AddField(
            model_name='pintsavailable',
            name='bloodgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.bloodgroup'),
        ),
        migrations.AlterField(
            model_name='pintsavailable',
            name='no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
