# Generated by Django 3.1.5 on 2021-01-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210127_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintsavailable',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.hospital'),
        ),
    ]
