# Generated by Django 3.1.5 on 2021-01-27 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_pintsavailable_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pintsavailable',
            name='bloodgroup',
        ),
        migrations.RemoveField(
            model_name='pintsavailable',
            name='hospital',
        ),
        migrations.AddField(
            model_name='hospital',
            name='bloodgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.bloodgroup'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pints',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.pintsavailable'),
        ),
    ]
