# Generated by Django 3.1.5 on 2021-01-28 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_donor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationorder',
            name='bloodgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.bloodgroup'),
        ),
        migrations.AddField(
            model_name='donationorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.donor'),
        ),
    ]
