# Generated by Django 3.1.5 on 2021-02-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210202_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
