# Generated by Django 3.1.5 on 2021-02-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210202_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donorid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
