# Generated by Django 3.1.5 on 2021-02-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0014_auto_20210202_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='group',
            field=models.ManyToManyField(choices=[('Hospital', 'Hospital'), ('Donor', 'Donor')], null=True, to='auth.Group'),
        ),
    ]
