# Generated by Django 3.1.5 on 2021-02-03 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20210203_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pintsavailable',
            name='hospital',
        ),
        migrations.AddField(
            model_name='hospital',
            name='pintsavailable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.pintsavailable'),
        ),
    ]
