# Generated by Django 3.1.5 on 2021-02-03 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20210203_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pintsavailable',
            old_name='no',
            new_name='count',
        ),
    ]
