# Generated by Django 3.1.5 on 2021-02-05 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0020_auto_20210205_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pintsavailable',
            name='hospital',
        ),
        migrations.AddField(
            model_name='pintsavailable',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
