# Generated by Django 3.1.5 on 2021-02-06 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20210205_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
                ('BloodGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.bloodgroup')),
            ],
        ),
        migrations.RenameField(
            model_name='donationorder',
            old_name='customer',
            new_name='donor',
        ),
        migrations.DeleteModel(
            name='PintsAvailable',
        ),
    ]
