# Generated by Django 3.1.5 on 2021-02-06 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20210206_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbank',
            old_name='BloodGroup',
            new_name='bloodgroup',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.hospital'),
        ),
    ]
