# Generated by Django 3.1.5 on 2021-02-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20210206_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbank',
            old_name='count',
            new_name='countno',
        ),
    ]
