# Generated by Django 3.1.5 on 2021-02-07 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20210206_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='hospital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.hospital'),
        ),
    ]
