# Generated by Django 3.1.5 on 2021-02-07 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20210207_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.hospital'),
        ),
    ]
