# Generated by Django 3.1.5 on 2021-02-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20210207_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='ABnegative',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ABpositive',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Anegative',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Apositive',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Bnegative',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Bpositive',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Onegative',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Opositive',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='bloodbank',
        ),
    ]
